
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 04 20:55:49 CEST 2014
//----------------------------------------------------

package cup.asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 9;
  public static final int AND = 20;
  public static final int MENOS = 5;
  public static final int LT = 16;
  public static final int OR = 21;
  public static final int INT = 19;
  public static final int NOT = 22;
  public static final int ELT = 17;
  public static final int TRUE = 23;
  public static final int GT = 14;
  public static final int ID = 2;
  public static final int POR = 6;
  public static final int NUM = 3;
  public static final int SEPSEC = 25;
  public static final int EGT = 15;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int PAP = 8;
  public static final int FALSE = 24;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int BOOL = 18;
  public static final int PUNTOCOMA = 11;
  public static final int NEQ = 12;
  public static final int ASIG = 10;
  public static final int MAS = 4;
}

