/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package javacc.asint;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int digito = 2;
  int parteEntera = 3;
  int eq = 4;
  int neq = 5;
  int gt = 6;
  int egt = 7;
  int lt = 8;
  int elt = 9;
  int and = 10;
  int or = 11;
  int not = 12;
  int bool = 13;
  int integer = 14;
  int tru = 15;
  int fals = 16;
  int sepsec = 17;
  int identificador = 20;
  int numeroEntero = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digito>",
    "<parteEntera>",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"bool\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"&&\"",
    "<token of kind 18>",
    "<token of kind 19>",
    "<identificador>",
    "<numeroEntero>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
